### ISSUE TITLE
host reference genome data

### ISSUE THREAD

**Issue by mcgml** [MRCIEU/gwas2vcf#44]
@explodecomputer the Broad have retired access to their FTP, I know we have copies of the genome FASTAs etc, do you know if we are hosting them externally?
Thanks
Matt

**Comment by explodecomputer** [comment]
not hosting them externally but we could link to it here https://github.com/mrcieu/gwasvcf
why did they retire access?

**Comment by mcgml** [comment]
outlined here: https://gatk.broadinstitute.org/hc/en-us/articles/360035890811-Resource-bundle 
their FTP is slow and has access issues etc so moved to Google cloud but only for hg38

**Comment by mcgml** [comment]
thanks I'll discuss with Peter

**Comment by mcgml** [comment]
also add chain files
