### ISSUE TITLE
Sample sizes formatted to only 6 significant digits

### ISSUE THREAD

**Issue by mja** [MRCIEU/gwas2vcf#47]
Sample sizes (the SS or NC records) greater than 1 million get truncated to six significant digits and formatted using E notation. For example, the number of cases "7654321" gets formatted as "7.65432e+06".

**Comment by mcgml** [comment]
Hi @mja 

Thanks for raising this. We have updated the VCF header so these fields are now integer which should solve the problem https://github.com/MRCIEU/gwas2vcf/commit/8d3c66b8d5ab4f609a52c0317b9ce1460b1b48e9.
