### ISSUE TITLE
Difficulty with --dbsnp/alias 

### ISSUE THREAD

**Issue by jinghuazhao** [MRCIEU/gwas2vcf#48]
Dear gwas2vcf team,

You have done a very nice job with gwas2vcf and I managed to convert out GWAS sumstats but I am having difficulty with --dbsnp/alias; without them I could get my .vcf but not with them; do you have any suggestions?

python main.py --out ${prot}.vcf.gz --data ${prot}.txt.gz \
                  --id ${prot} --ref human_g1k_v37.fasta --json gwas2vcf.json \
                  --dbsnp snp154_GCF_000001405.25.gz \
                  --alias hg19.chromAlias.tsv

A chunk of data is shown here,
chr	pos	snpid	a1	a2	af	b	se	logp	n
1	10177	chr1:10177_A_AC	A	AC	0.6598	-0.0391	0.0223	1.1	6879

Thank you!

Jing Hua

**Comment by jinghuazhao** [comment]
Thanks for getting back to me, it sounds the alias is simply chrom\tchr pair? I did try that as well. The reference file agrees with your indication. Do you have an example? That would certainly help!

I have those dbsnp and alias files as these,
# hg19
# wget https://ftp.ncbi.nih.gov/snp/archive/b154/VCF/GCF_000001405.25.gz -O snp154_GCF_000001405.25.gz
# wget https://ftp.ncbi.nih.gov/snp/archive/b154/VCF/GCF_000001405.25.gz.tbi -O snp154_GCF_000001405.25.gz.tbi
gunzip -c snp154_GCF_000001405.25.gz > snp154_GCF_000001405.25
# alias file for chomosomes
# https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/chromToUcsc

**Comment by mcgml** [comment]
Hi @jinghuazhao

Thanks for the message. 

Here is an example for running gwas2vcf.

```sh
# obtain test gwas summary stats
wget https://raw.githubusercontent.com/MRCIEU/gwas2vcfweb/master/app/tests/data/example.1k.txt
```

```
# JSON param file
{
  "chr_col": 0,
  "pos_col": 1,
  "snp_col": 2,
  "ea_col": 3,
  "oa_col": 4,
  "beta_col": 5,
  "se_col": 6,
  "ncontrol_col": 7,
  "pval_col": 8,
  "eaf_col": 9,
  "delimiter": "\t",
  "header": true,
  "build": "GRCh37"
}
```

```sh
# map to GWAS-VCF
SumStatsFile=/data/example.1k.txt
RefGenomeFile=/data/human_g1k_v37.fasta
ParamFile=/data/params.json
DbSnpVcfFile=/data/dbsnp.v153.b37.vcf.gz
VcfFileOutPath=/data/out.vcf
ID="test"

python /app/main.py \
--data ${SumStatsFile} \
--json ${ParamFile} \
--id ${ID} \
--ref ${RefGenomeFile} \
--dbsnp ${DbSnpVcfFile} \
--out ${VcfFileOutPath} \
--alias /app/alias.txt
```

Assuming hg19/b37 you can use the following links:
- [RefGenomeFile](https://github.com/MRCIEU/gwas2vcf#reference-fasta)
- [DbSnpVcfFile](https://github.com/MRCIEU/gwas2vcf#dbsnp)
- [alias.txt](https://github.com/MRCIEU/gwas2vcf/blob/master/alias.txt)

I hope this helps

**Comment by jinghuazhao** [comment]
Hi again, I managed to get all of the files as suggested and git pull the latest code but with the same error -- do I miss anything? 

  File "../main.py", line 182, in <module>
    main()
  File "../main.py", line 121, in main
    (key, val) = line.strip().split("\t")

**Comment by mcgml** [comment]
are you using Python2? I'm using 3.8, does that explain the issue ?

**Comment by jinghuazhao** [comment]
Hi, it works now with your examples. I also git pull to update gwas2vcf. BTW it does seem more intuitive to rework the dbSNP distribution. Thank you!

**Comment by jinghuazhao** [comment]
I used Python 3.7.7 and the alias.txt file was in html and not ASCII format.

**Comment by mcgml** [comment]
great thanks

**Comment by jinghuazhao** [comment]
Thank you!
