### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by edwardhumphreys** [MRCIEU/gwas2vcf#50]
I have setup docker on a Mac and can run main.py without errors using the following. 

docker run -v /Users/username/Documents/dockerfiles:/Users/username/Documents/dockerfiles --name gwas2vcf -it gwas2vcf:latest python main.py --data /Users/username/Documents/dockerfiles/data/gwas.tsv.gz --json /app/params.json --id ID --ref /Users/username/Documents/dockerfiles/data/human_g1k_v37.fasta --dbsnp /Users/username/Documents/dockerfiles/data/dbsnp.v153.b37.vcf.gz --out /Users/username/Documents/dockerfiles/data/out.vcf --alias ./alias.txt

Runtime is around 4 hours but results in no output file. I have also ran in with DEBUG and there appears to be no error messages.

**Comment by mcgml** [comment]
Hi @edwardhumphreys what does this file look like ```/Users/username/Documents/dockerfiles/data/out.vcf```. Another option if you only plan to convert a few GWAS is to use the web service available from <https://vcf.mrcieu.ac.uk/>

**Comment by edwardhumphreys** [comment]
The /Users/username/Documents/dockerfiles/data/out.vcf files does not exist.

**Comment by mcgml** [comment]
Hi @edwardhumphreys 

Sorry for the slow reply.

You'll need to create a ```params.json``` file which tells the script which columns in your GWAS file are the chromosome, position, eaf, p etc. There's an example [here](https://github.com/MRCIEU/gwas2vcf/blob/master/README.md#example) and below for you to update relevant to your file.

```
{
  "chr_col": 0,
  "pos_col": 1,
  "snp_col": 2,
  "ea_col": 3,
  "oa_col": 4,
  "beta_col": 5,
  "se_col": 6,
  "ncontrol_col": 7,
  "pval_col": 8,
  "eaf_col": 9,
  "delimiter": "\t",
  "header": true,
  "build": "GRCh37"
}
```

Assuming the ```params.json``` is in ```/Users/username/Documents/dockerfiles/data``` the following command should work.

```
docker run \
-v /Users/username/Documents/dockerfiles:/Users/username/Documents/dockerfiles \
--name gwas2vcf \
-it gwas2vcf:latest \
python main.py \
--data /Users/username/Documents/dockerfiles/data/gwas.tsv.gz \
--json /Users/username/Documents/dockerfiles/data/params.json \
--id ID \
--ref /Users/username/Documents/dockerfiles/data/human_g1k_v37.fasta \
--dbsnp /Users/username/Documents/dockerfiles/data/dbsnp.v153.b37.vcf.gz \
--out /Users/username/Documents/dockerfiles/data/out.vcf \
--alias ./alias.txt
```

As a quick test you could try just running the first few rows of your GWAS

```
# take first ten rows from GWAS
zcat /Users/username/Documents/dockerfiles/data/gwas.tsv.gz | head | gzip -c > /Users/username/Documents/dockerfiles/data/gwas.h.tsv.gz

# conver to VCF
docker run \
-v /Users/username/Documents/dockerfiles:/Users/username/Documents/dockerfiles \
--name gwas2vcf \
-it gwas2vcf:latest \
python main.py \
--data /Users/username/Documents/dockerfiles/data/gwas.h.tsv.gz \
--json /Users/username/Documents/dockerfiles/data/params.json \
--id ID \
--ref /Users/username/Documents/dockerfiles/data/human_g1k_v37.fasta \
--dbsnp /Users/username/Documents/dockerfiles/data/dbsnp.v153.b37.vcf.gz \
--out /Users/username/Documents/dockerfiles/data/out.vcf \
--alias ./alias.txt
```

Let me know if you still have issues

Thanks
Matt

**Comment by edwardhumphreys** [comment]
Many thanks. I had to use gzcat instead of zcat.

Converting the first 10 row works and produces an vcf output however when switching back to the full GWAS I get no output file. Both using your docker command and with the GWAS and the short GWAS coming from the same directory.

**Comment by mcgml** [comment]
@edwardhumphreys Thanks, I'd really like to get to the bottom of this. Would you be able to share your GWAS file? If it's public could you share the link? Or if private transfer using https://wetransfer.com? My email is ml18692@bristol.ac.uk.

**Comment by mcgml** [comment]
Hi @edwardhumphreys 

Thanks for the link. The following code works as expected. Are you able to replicate this on your machine?

```
# download data
wget http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST90012001-GCST90013000/GCST90012102/GCST90012102_buildGRCh37.tsv.gz
gzip -d GCST90012102_buildGRCh37.tsv.gz

# run
docker run \
--name issue50 \
-v $PWD:/Users/username/Documents/dockerfiles \
-v /path/to/fasta:/path/to/fasta \
-v /path/to/dbsnp:/path/to/dbsnp \
-it -d \
gwas2vcf:latest \
python main.py \
--data /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.tsv \
--json /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.json \
--id ID \
--ref /path/to/fasta/human_g1k_v37.fasta \
--dbsnp /path/to/dbsnp:/path/to/dbsnp/dbsnp.v153.b37.vcf.gz \
--out /Users/username/Documents/dockerfiles/out.vcf \
--alias ./alias.txt
```

```
cat GCST90012102_buildGRCh37.json 
{
  "chr_col": 1,
  "pos_col": 2,
  "snp_col": 0,
  "ea_col": 3,
  "oa_col": 4,
  "beta_col": 7,
  "se_col": 8,
  "pval_col": 9,
  "eaf_col": 5,
  "delimiter": "\t",
  "header": true,
  "build": "GRCh37"
}
```

**Comment by edwardhumphreys** [comment]
RE /path/to/fasta/ & /path/to/dbsnp, can I put the fasta and dbsnp in /Users/username/Documents/dockerfiles/?

**Comment by mcgml** [comment]
Sure, you can remove those mounts. Just noticed a typo, fixed below.

```
docker run \
--name issue50 \
-v /Users/username/Documents/dockerfiles:/Users/username/Documents/dockerfiles \
-it -d \
gwas2vcf:latest \
python main.py \
--data /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.tsv \
--json /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.json \
--id ID \
--ref /Users/username/Documents/dockerfiles/human_g1k_v37.fasta \
--dbsnp /Users/username/Documents/dockerfiles/dbsnp.v153.b37.vcf.gz \
--out /Users/username/Documents/dockerfiles/out.vcf \
--alias ./alias.txt
```

**Comment by edwardhumphreys** [comment]
I get no output file as before:

`docker run --name issue50 -v /Users/username/Documents/dockerfiles:/Users/username/Documents/dockerfiles -it -d gwas2vcf:latest python main.py --data /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.tsv --json /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.json --id ID --ref /Users/username/Documents/dockerfiles/human_g1k_v37.fasta --dbsnp /Users/username/Documents/dockerfiles/dbsnp.v153.b37.vcf.gz --out /Users/username/Documents/dockerfiles/out.vcf --alias ./alias.txt`

This is the command output

```
2021-05-20 14:55:47,696 INFO Gwas2VCF 1.3.2

2021-05-20 14:55:47,697 INFO Arguments: {'out': '/Users/username/Documents/dockerfiles/out.vcf', 'data': '/Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.tsv', 'ref': '/Users/username/Documents/dockerfiles/human_g1k_v37.fasta', 'dbsnp': '/Users/username/Documents/dockerfiles/dbsnp.v153.b37.vcf.gz', 'json': '/Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.json', 'id': 'ID', 'cohort_controls': None, 'cohort_cases': None, 'csi': False, 'log': 'INFO', 'alias': './alias.txt'}

2021-05-20 14:55:47,697 INFO Reading JSON parameters

2021-05-20 14:55:47,709 INFO Parameters: {'build': 'GRCh37', 'snp_col': 0, 'eaf_col': 5, 'delimiter': '\t', 'pos_col': 2, 'ea_col': 3, 'se_col': 8, 'oa_col': 4, 'header': True, 'pval_col': 9, 'beta_col': 7, 'chr_col': 1}

2021-05-20 14:55:47,710 INFO Checking input arguments

2021-05-20 14:55:47,986 INFO Reading summary stats and mapping to FASTA: /Users/username/Documents/dockerfiles/GCST90012102_buildGRCh37.tsv

2021-05-20 14:55:47,987 INFO Reading plain text file

2021-05-20 14:55:47,993 INFO Skipping header: variant_id chromosome base_pair_location effect_allele other_allele effect_allele_frequency imputation_quality beta standard_error p_value
```

**Comment by mcgml** [comment]
Hi @edwardhumphreys 

Thanks for the update, sorry you're still having difficulties. 

I think trying a different directory would be a good idea, iCloud will slow things down and could cause issues. Also you could check your previous attempts have finished successfully with ```docker ps -a | grep gwas2vcf```. If it says "Exited (0)" it finished without error but did not create the output file.

Best wishes
Matt

**Comment by edwardhumphreys** [comment]
That is really useful. Exit code is 137. Which could be OutOfMemory, that would make sense of the shorter file working. I will increase resources (from 2GB) and run again.

Many thanks

**Comment by edwardhumphreys** [comment]
That fixed my issue, adding 12GB of memory.

**Comment by Xuemin-Wang** [comment]
> https://vcf.mrcieu.ac.uk/

Has the web service been moved to another place? It's an oven to air fryer converter.
