### ISSUE TITLE
compress fasta files used in example

### ISSUE THREAD

**Issue by darked89** [MRCIEU/gwas2vcf#51]
Hello,

downloading 3G human genome fasta files from your server, i.e. 

http://fileserve.mrcieu.ac.uk/ref/2.8/b37/human_g1k_v37.fasta

takes several minutes. Reducing the download size by it by compressing fasta with gzip or even zstd would reduce the time for downloads. Zstd -11 produces file 0.27 of the original size while its decompression on 8 threads i7 takes ~8s. 

DK

**Comment by mcgml** [comment]
Thanks for the suggestion @darked89. This has been updated
