### ISSUE TITLE
alias file

### ISSUE THREAD

**Issue by tillandlauer** [MRCIEU/gwas2vcf#53]
Hi,
I think your alias.txt contains a mistake. You list:
25	MT
However, at least in PLINK, only 26 is MT, 25 is XY.
By the way, it would be great if the documentation mentioned that your hg19 and hg38 files use different chromosome codes.
Thanks for looking into this,
Till

**Comment by mcgml** [comment]
Thanks @tillandlauer I have updated the alias file and docs with ac87e341cd6da63c3079da70dede02249df1a672 and d27300cc3aa4478f03490ddd70c78c8c8fa21695.

Let me know if you anything is still unclear

Thanks
Matt
