### ISSUE TITLE
different naming schemes in dbsnp.v153.b37.vcf.gz vs dbsnp.v153.hg38.vcf.gz

### ISSUE THREAD

**Issue by darked89** [MRCIEU/gwas2vcf#54]
Hello,

using two input TSV files with the same chromosome naming scheme (1, 2, etc.)  
1. example.1k.txt (run with: ```human_g1k_v37.fasta``` & ```dbsnp.v153.b37.vcf.gz```
2. a subset of finngen_R5_D3_SARCOIDOSIS.tsv (header & SNPs for chromosome 22 only)  run using: ```Homo_sapiens_assembly38.fasta``` & ```dbsnp.v153.hg38.vcf.gz```

 I got a proper VCF with  example.1k.txt and just a VCF header for the finngen input. 
All  the genome and dbSNP files were downloaded using links from from your repository README.md.

I have discovered that i.e. dbSNP files have a different naming schemes:

```
bcftools view -h  dbsnp.v153.b37.vcf.gz | grep '^##cont'

# result

##contig=<ID=1,length=249250621>
##contig=<ID=2,length=243199373>
##contig=<ID=3,length=198022430>
##contig=<ID=4,length=191154276>
##contig=<ID=5,length=180915260>
##contig=<ID=6,length=171115067>
##contig=<ID=7,length=159138663>
##contig=<ID=8,length=146364022>
##contig=<ID=9,length=141213431>
##contig=<ID=10,length=135534747>
##contig=<ID=11,length=135006516>
##contig=<ID=12,length=133851895>
##contig=<ID=13,length=115169878>
##contig=<ID=14,length=107349540>
##contig=<ID=15,length=102531392>
##contig=<ID=16,length=90354753>
##contig=<ID=17,length=81195210>
##contig=<ID=18,length=78077248>
##contig=<ID=19,length=59128983>
##contig=<ID=20,length=63025520>
##contig=<ID=21,length=48129895>
##contig=<ID=22,length=51304566>
##contig=<ID=X,length=155270560>
##contig=<ID=Y,length=59373566>
##contig=<ID=MT,length=16569>
<snip>

```
### hg38

```
bcftools view -h  dbsnp.v153.hg38.vcf.gz | grep '^##cont' | 

# result

##contig=<ID=chr1,length=248956422,assembly=38>
##contig=<ID=chr2,length=242193529,assembly=38>
##contig=<ID=chr3,length=198295559,assembly=38>
##contig=<ID=chr4,length=190214555,assembly=38>
##contig=<ID=chr5,length=181538259,assembly=38>
##contig=<ID=chr6,length=170805979,assembly=38>
##contig=<ID=chr7,length=159345973,assembly=38>
##contig=<ID=chr8,length=145138636,assembly=38>
##contig=<ID=chr9,length=138394717,assembly=38>
##contig=<ID=chr10,length=133797422,assembly=38>
##contig=<ID=chr11,length=135086622,assembly=38>
##contig=<ID=chr12,length=133275309,assembly=38>
##contig=<ID=chr13,length=114364328,assembly=38>
##contig=<ID=chr14,length=107043718,assembly=38>
##contig=<ID=chr15,length=101991189,assembly=38>
##contig=<ID=chr16,length=90338345,assembly=38>
##contig=<ID=chr17,length=83257441,assembly=38>
##contig=<ID=chr18,length=80373285,assembly=38>
##contig=<ID=chr19,length=58617616,assembly=38>
##contig=<ID=chr20,length=64444167,assembly=38>
##contig=<ID=chr21,length=46709983,assembly=38>
##contig=<ID=chr22,length=50818468,assembly=38>
##contig=<ID=chrX,length=156040895,assembly=38>
##contig=<ID=chrY,length=57227415,assembly=38>
##contig=<ID=chrM,length=16569,assembly=38>
<snip>
```

Can you kindly provide instructions about the way you use to synchronize the chromosome/contigs naming schemes for dbSNP VCF relase downloaded directly from i.e: 
https://ftp.ncbi.nih.gov/snp/latest_release/VCF/
??

It is not clear without investigating the code what is being done in the background to handle apparently different chromosome names in the input TSV, genomic fasta and dbSNP.

Many thanks for your help

Darek Kedra

**Comment by mcgml** [comment]
Hi @darked89 

The harmonisation works by mapping all variants to a supplied FASTA. The chr prefix issue can be avoided by providing an alias file to specify the mapping from your GWAS summary statistics to hg38 (assuming the builds are the same and only the chr prefix is different).

For example create alias file mapping chromosomes 1-22 & X to chr1-chr22 & chrX

```sh
for i in {1..22}; do echo -e "$i\tchr$i"; done > alias-finngenn.txt
echo -e "X\tchrX" >> alias-finngenn.txt
```
Then run the harmonisation with your new alias file

```sh
python main.py \
--data gwas.txt \
--json params.json \
--ref hg38.fa \
--dbsnp dbsnp.hg38.vcf \
--out gwas.vcf \
--alias alias-finngenn.txt
```

Let me know if this doesn't fix the problem

Thanks
Matt

**Comment by darked89** [comment]
Thank you for a prompt answer/resolving the issue. 

For the latest dbSNP (155, GRCh38)  from: https://ftp.ncbi.nih.gov/snp/latest_release/VCF/GCF_000001405.39.gz

I have changed the names in the dbSNP VCF using infor from:
https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/405/GCF_000001405.26_GRCh38/GCF_000001405.26_GRCh38_assembly_report.txt

file: hg38_rename_chrom_names.tsv
```
NC_000001.11    1
NC_000002.12    2
NC_000003.12    3
NC_000004.12    4
NC_000005.10    5
NC_000006.12    6
NC_000007.14    7
NC_000008.11    8
NC_000009.12    9
NC_000010.11    10
NC_000011.10    11
NC_000012.12    12
NC_000013.11    13
NC_000014.9     14
NC_000015.10    15
NC_000016.10    16
NC_000017.11    17
NC_000018.10    18
NC_000019.10    19
NC_000020.11    20
NC_000021.9     21
NC_000022.11    22
NC_000023.11    X
NC_000024.10    Y
NC_012920.1     MT
```

command:
```(bash)
bcftools annotate \
--rename-chrs hg38_rename_chrom_names.tsv \
--output-type z \
--output /data/dbSNP_155_clean.vcf.gz GCF_000001405.39.gz
```
hope it helps

DK

**Comment by mcgml** [comment]
Thanks, I updated the docs https://github.com/MRCIEU/gwas2vcf/blob/master/README.md#dbsnp
