### ISSUE TITLE
reference genome base checking

### ISSUE THREAD

**Issue by darked89** [MRCIEU/gwas2vcf#58]
Hello,

gwas2vcf seems to be dropping (BTW, correct behavior) lines where TSV input REF base does not match the genomic fasta base at that position. By accident (BED file with chromosomes starting with 1 combined with pyfaidx) I noticed that the greatly reduced in size VCF result is still produced by gwas2vcf.

Would it be possible to add some extra check or big fat warning that the number of the dropped positions exceeds some arbitrary limit? 
I was lucky enough to have an intact VCF from the previous gwas2vcf run using not corrupted all contigs genomic fasta so the difference was obvious. 

Kind regards,

Darek Kedra

**Comment by mcgml** [comment]
Thanks @darked89. Implemented with 770d3b3
