### ISSUE TITLE
 pickle.dump(result, results): no space left on the device

### ISSUE THREAD

**Issue by darked89** [MRCIEU/gwas2vcf#59]
Hello,

while running multiple (~3000 TSV from R5 Finngen) jobs on a cluster I encountered: 
```
Traceback (most recent call last):
  File "/app/main.py", line 182, in <module>
    main()
  File "/app/main.py", line 130, in main
    gwas, idx, sample_metadata = Gwas.read_from_file(
  File "/app/gwas.py", line 342, in read_from_file
    pickle.dump(result, results)
OSError: [Errno 28] No space left on device
```

I am running the 1.3.1 version inside of the Singularity container. The /tmp partitions on the computing nodes apparently can be filled in be it by multiple gwas2vcf jobs running on the node or other user jobs. 
Setting up $TMP to some other larger directory (i.e. ```/home/username/tmp``` ) before invoking ```singularity exec gwas2vcf_1.3.1.sif```  does work, but one has to make sure that the aforementioned $TMP directory is accessible from the inside of the Singularity container. No ```--no-home``` switch in the example above.

May I suggest to wrap the ```pickle.dump(result, results)``` in try: except and printing out ``` tempfile.gettempdir()```  for the easier debugging?

Hope it helps

Darek Kedra

**Comment by mcgml** [comment]
Thanks @darked89 I have added the suggestion with 34a1645
