### ISSUE TITLE
How to parse GWAS from PMID: 30224653

### ISSUE THREAD

**Issue by vforget** [MRCIEU/gwas2vcf#60]
Hi,

I noticed that GWAS from 30224653 is present here:

https://gwas.mrcieu.ac.uk/files/ieu-b-38/ieu-b-38_report.html

Was data obtained from the following:

ftp://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/GCST006001-GCST007000/GCST006624

If so, I noted that the chrom and position are not separate columns, but part of the SNP ID.

Was gwas2vcf used to parse this for storing into https://gwas.mrcieu.ac.uk?

Thanks,

Vince

**Comment by mcgml** [comment]
Hi @vforget

The dataset did not come from the EBI and was pre-processed by a colleague so not sure if the data originated from the same file. Yes, after pre-processing the GWAS txt file was converted to GWAS-VCF and imported into our database.

Best wishes
Matt

**Comment by mcgml** [comment]
@vforget but in general you would need to split the concatenated field into two columns before converting to VCF.

Thanks
Matt
