### ISSUE TITLE
could not read from remote repository

### ISSUE THREAD

**Issue by jielab** [MRCIEU/gwas2vcf#64]
hi, there:

I am following the instruction https://mrcieu.github.io/gwas2vcf/install/ here, and run **git clone git@github.com:MRCIEU/gwas2vcf.git**. However, please see the following screenshot, it does not work.

<img width="519" alt="11" src="https://user-images.githubusercontent.com/26947455/132602437-8bdb2866-0a01-4947-ac23-485d8ed8765a.png">

Can you please kindly check that the repository is still there for downloading?

Best regards,
Jie

**Comment by jielab** [comment]
I got it resolved, by **git clone https://github.com/MRCIEU/gwas2vcf.git**

maye you guys want to update this command.

Best regards,
Jie

**Comment by mcgml** [comment]
Thanks @jielab, docs updated
