### ISSUE TITLE
ValueError: fetch requires an index

### ISSUE THREAD

**Issue by jielab** [MRCIEU/gwas2vcf#65]
Hi, I got the error of **ValueError: fetch requires an index**. Please see the screenshot below. 

![fasta](https://user-images.githubusercontent.com/26947455/132768921-f4de422b-cb46-4949-9eba-4fb9f4fc3f50.png)

I did download the fasta file and the .fai file using **wget http://fileserve.mrcieu.ac.uk/ref/2.8/b37/human_g1k_v37.fasta.gz**

I also manually gunzip this fasta.gz file and **bgzip** it again. I also manually used **samtools faidx** to re-create the .fai file. However, none of these solutions worked. Can you please let me know what might have gone wrong here?
It is very frustrating that my very first test run did not work, after i tried for a hour ...

Thanks!

Jie

**Comment by mcgml** [comment]
Hi @jielab 

Sorry for confusion. Please try using uncompressed FASTA and fai.

Best wishes
Matt
