### ISSUE TITLE
OSError: error when opening file `human_g1k_v37.fasta.gz`

### ISSUE THREAD

**Issue by jielab** [MRCIEU/gwas2vcf#66]
Hi, guys:

I followed the instruction to download the human_g1k_v37.fasta.gz file 2 times. But as shown in the following screenshot, GWAS2VCF keeps complaining that this file could not be read. 

![image](https://user-images.githubusercontent.com/26947455/132905112-3162141e-9001-4837-b34d-9c06325e685b.png)

Do you guys have a md5 file for me to check I got the correct file?

Thank you very much & best regards,
Jie

**Comment by mcgml** [comment]
Hi @jielab 

The FASTA file and index should be uncompressed ```gzip -d <file>```. Sorry for the confusion, I will update the docs.

Thanks
Matt
